sudo: required
dist: trusty
language: scala
scala:
  - 2.12.4
jdk:
  - oraclejdk8

services:
  - mysql

before_install:
  - mysql -e "create database IF NOT EXISTS tpf;" -uroot
  - mysql -u root -e "CREATE USER 'tpf'@'localhost' IDENTIFIED BY 'tpf';"
  - mysql -u root -e "GRANT ALL ON tpf.* TO 'tpf'@'localhost';"

script:
  - sbt scalafmt::test
  - sbt test:scalafmt::test
  - sbt flywayClean
  - sbt flywayMigrate
  - sbt flywayInfo
  - sbt test
  - sbt dist